### ISSUE TITLE
classifier training error

### ISSUE THREAD

**Issue by 0Godness** [JuliaWolleb/diffusion-anomaly#1]
creating data loader...
dataset is chexpert
creating optimizer...
training classifier model...
step 0
classnames ['diseased', 'healthy', 'diseased', 'diseased', 'diseased', 'healthy', 'healthy', 'healthy']
len 8
len 8
len 8
lenloader 8
len 8
path patient01104_study1
path patient00485_study2
path patient00124_study2
IS CHEXPERT
labels tensor([1], device='cuda:0')
h1 torch.Size([1, 8192])
Traceback (most recent call last):
  File "/home/Diffusion Models/diffusion-anomaly/scripts/classifier_train.py", line 191, in main
    losses = forward_backward_log(data, step + resume_step)
  File "/home/Diffusion Models/diffusion-anomaly/scripts/classifier_train.py", line 138, in forward_backward_log
    logits = model(sub_batch, timesteps=sub_t)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/syg/Diffusion Models/diffusion-anomaly/./guided_diffusion/unet.py", line 955, in forward
    return self.out(h)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x8192 and 256x2)

I just use your original code and 'data' to train the classifier, but i got these errors. Could you please help to solve the error? And the class name is 8 which is inconsistent to the paper setting 2. I dont know whether I run it using wrong setting. Hoping for your detailed answers! Thank you!

**Comment by JuliaWolleb** [comment]
Hi
How did you set the path to your training data? It should go to _data/chexpert/training._ Then, the length of the class names should be 6 instead of 8, because you have only 6 images in your training set in this mini-example. You still have only 2 classes, which is 'healthy' and 'diseased', so that should work fine.

Regarding your error, I made a change to the file _guided_diffusion/unet.py_. Let me know whether this fixed the issue.

Best,
Julia

**Comment by 0Godness** [comment]
Thanks for your kind answers. Yes, it works! So the one .npy file represents one image? Could you provide the transfer code and I want to use custom dataset. 
Thanks again!

**Comment by JuliaWolleb** [comment]
yes, one .npy file represents one image. Would maybe be a better idea to store them in another format.
What do you mean by transfer code?

**Comment by zideliu** [comment]
> yes, one .npy file represents one image. Would maybe be a better idea to store them in another format. What do you mean by transfer code?

transfer cheXpert dataset to .npy?

And if possible, could you provide the code for processing the brasts dataset?
The format of the dataset I downloaded is not the same as the format required by the code

**Comment by ZZZGGGG** [comment]
> Hi How did you set the path to your training data? It should go to _data/chexpert/training._ Then, the length of the class names should be 6 instead of 8, because you have only 6 images in your training set in this mini-example. You still have only 2 classes, which is 'healthy' and 'diseased', so that should work fine.
> 
> Regarding your error, I made a change to the file _guided_diffusion/unet.py_. Let me know whether this fixed the issue.
> 
> Best, Julia

Hello Professor, I also have such a question. When I am training the classifier module, the loss will not converge and fluctuate very strangely. Is this normal?

**Comment by JuliaWolleb** [comment]
Hi

Yes this is normal and due to the fact that the input images contain various levels of noise.

**Comment by ZZZGGGG** [comment]
> Hi
> 
> Yes this is normal and due to the fact that the input images contain various levels of noise.

Thank you for your reply. May I ask you another question? How do I tell if the classifier model has been trained? Thank you, Professor.

**Comment by JuliaWolleb** [comment]
That is usually hard to tell. You can validate by computing the classification scores on non-noisy images.

**Comment by ZZZGGGG** [comment]
> That is usually hard to tell. You can validate by computing the classification scores on non-noisy images.
Ok, thank you very much for your sharing and clarification

**Comment by tungnthust** [comment]
> That is usually hard to tell. You can validate by computing the classification scores on non-noisy images.

Could you kindly share train/test split (patient ids for each set) and hyperparmeters for training classifier for BRATS dataset (i.e learning_rate, batch_size, anneal_lr, weight_decay, dropout) ? I tried your training settings in README, but it does not produce good results (much worse than your pretrained classifier checkpoint you provided). I refered to classifer hyperparmeters used in openai/guided_diffusion repository, it is different from your settings cited in README. So I want to know your exact parameters to reproduce your results. Thank you very much.

**Comment by op1009** [comment]
Has anyone figured out the correct hyper parameters for classifier training ?
Train loss varies between 0.6 to 0.3 throughout, irrespective of no of iterations. @JuliaWolleb can you share actual hyper param you have used.

**Comment by JuliaWolleb** [comment]
It is normal that the classifier loss does not go down to 0, since we feed images of changing noise levels.
The hyperparameters used for the classifier training are specified in the classifier flags: `CLASSIFIER_FLAGS="--image_size 256 --classifier_attention_resolutions 32,16,8 --classifier_depth 4 --classifier_width 32 --classifier_pool attention --classifier_resblock_updown True --classifier_use_scale_shift_norm True"` . The other hyperparameters are defined [here](https://github.com/JuliaWolleb/diffusion-anomaly/blob/509643c3c15fc5af7d4712aa7b1e8ba8a06214ff/scripts/classifier_train.py#L249). 
As a test, you can try to run the training of the classifier on  non-noisy images and see whether the loss function converges.
